// página de array para manter o código mais limpo
const produtos = [
    {
      titulo: "Lorem Ipsum Dolor 1",
      descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      imagem: "https://via.placeholder.com/200",
      preco: 100.0,
      desconto: "R$95,00 com Pix",
      parcelas: "2 x de R$47,50 sem juros",
    },
    {
      titulo: "Lorem Ipsum Dolor 2",
      descricao: "Quisque sit amet justo sit amet ligula vestibulum gravida.",
      imagem: "https://via.placeholder.com/200",
      preco: 120.0,
      desconto: "R$114,00 com Pix",
      parcelas: "2 x de R$57,00 sem juros",
    },
    {
      titulo: "Lorem Ipsum Dolor 3",
      descricao: "Curabitur vel lacus eget justo elementum tincidunt.",
      imagem: "https://via.placeholder.com/200",
      preco: 150.0,
      desconto: "R$142,50 com Pix",
      parcelas: "2 x de R$71,75 sem juros",
    },
    {
      titulo: "Lorem Ipsum Dolor 4",
      descricao: "Vestibulum consequat eros ut suscipit posuere.",
      imagem: "https://via.placeholder.com/200",
      preco: 90.0,
      desconto: "R$85,50 com Pix",
      parcelas: "2 x de R$45,00 sem juros",
    },
    {
      titulo: "Lorem Ipsum Dolor 5",
      descricao: "Nulla facilisi. Donec viverra sollicitudin tortor.",
      imagem: "https://via.placeholder.com/200",
      preco: 110.0,
      desconto: "R$104,50 com Pix",
      parcelas: "2 x de R$52,25 sem juros",
    },
    {
      titulo: "Lorem Ipsum Dolor 6",
      descricao: "Aenean auctor, mauris sit amet ultricies porttitor.",
      imagem: "https://via.placeholder.com/200",
      preco: 80.0,
      desconto: "R$76,00 com Pix",
      parcelas: "2 x de R$38,00 sem juros",
    },
    {
      titulo: "Lorem Ipsum Dolor 7",
      descricao: "Mauris hendrerit sapien eu dui vehicula, a cursus eros.",
      imagem: "https://via.placeholder.com/200",
      preco: 130.0,
      desconto: "R$123,50 com Pix",
      parcelas: "2 x de R$61,75 sem juros",
    },
    {
      titulo: "Lorem Ipsum Dolor 8",
      descricao: "Ut quis lectus facilisis, consectetur purus et.",
      imagem: "https://via.placeholder.com/200",
      preco: 95.0,
      desconto: "R$90,25 com Pix",
      parcelas: "2 x de R$45,10 sem juros",
    },
    {
      titulo: "Lorem Ipsum Dolor 9",
      descricao: "Integer posuere ligula a augue dictum fermentum.",
      imagem: "https://via.placeholder.com/200",
      preco: 140.0,
      desconto: "R$133,00 com Pix",
      parcelas: "2 x de R$62,50 sem juros",
    },
    {
      titulo: "Lorem Ipsum Dolor 10",
      descricao: "Donec consectetur eros quis bibendum vestibulum.",
      imagem: "https://via.placeholder.com/200",
      preco: 60.0,
      desconto: "R$57,00 com Pix",
      parcelas: "2 x de R$30,00 sem juros",
    },
    {
      titulo: "Lorem Ipsum Dolor 11",
      descricao: "Morbi molestie justo at nulla malesuada, id efficitur magna.",
      imagem: "https://via.placeholder.com/200",
      preco: 70.0,
      desconto: "R$66,50 com Pix",
      parcelas: "2 x de R$33,25 sem juros",
    },
    {
      titulo: "Lorem Ipsum Dolor 12",
      descricao: "Aliquam sit amet purus in augue fermentum malesuada.",
      imagem: "https://via.placeholder.com/200",
      preco: 85.0,
      desconto: "R$80,75 com Pix",
      parcelas: "2 x de R$40,35 sem juros",
    },
  ];

  export default produtos;